[supervisord]
nodaemon=true
logfile=/dev/stdout          ; yeh same rakho
logfile_maxbytes=0           ; <--- Yeh add karo (0 = infinite, no rollover/rotation attempt)
loglevel=info

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0    ; yeh bhi 0 kar do
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:php-fpm]
command=php-fpm --nodaemonize
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0